server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

openapi:
  servers:
    - url: "http://api-gateway:8080"
      description: "API Gateway Server"
    - url: "http://user-service:8081"
      description: "LOCAL ENV"
