namespace: test
replicaCount: 1

image:
  repository: "021891582190.dkr.ecr.ap-south-1.amazonaws.com/user-service-image"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

ingress:
  enabled: false